version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: apple_academy_backend
    restart: always
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Academy2024#@!
      - DB_NAME=apple_academy
      - SECRET_KEY=sua_chave_secreta_muito_segura_aqui
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./backend:/app/backend
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: apple_academy_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: apple_academy_manager-db-1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Academy2024#@!
      MYSQL_DATABASE: apple_academy
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
