services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: apple_academy_backend
    restart: always
    environment:
      - DB_TYPE=mysql
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=Academy2024#@!
      - DB_NAME=apple_academy
      - SECRET_KEY=sua_chave_secreta_muito_segura_aqui
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./backend:/app/backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: apple_academy_client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

